### ISSUE TITLE
App Crashing on Firebase from the message object.

### ISSUE THREAD

**Issue by Toters-Mohammad-Tabbara** [twilio/twilio-conversations-demo-android-kotlin#40]
I am using conversations SDK v3.1.0 message.dateCreatedAsDate causes the following crash for some users.
```
Fatal Exception: java.lang.NullPointerException: parseIso8601DateTime(dateCreated) must not be null
       at com.twilio.conversations.MessageImpl.getDateCreatedAsDate(MessageImpl.kt:55)
       at -.chat.ChatAdapter$TextAgentViewHolder.bindView(ChatAdapter.kt:405)
       at -.chat.ChatAdapter.onBindViewHolder(ChatAdapter.kt:138)
       at -.chat.ChatAdapter.onBindViewHolder(ChatAdapter.kt:39)
       at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:678)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:1330)
       at android.view.View.layout(View.java:24461)
       at android.view.ViewGroup.layout(ViewGroup.java:7412)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4601)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4023)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2911)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10458)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:797)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by berkus** [comment]
Thanks for the report!

Could you provide a bit more details for which users and which messages it happens? Ideallly, provide a detailed log with VERBOSE level from one of the occurences.

**Comment by Toters-Mohammad-Tabbara** [comment]
Regarding user identification should be client.1225558 as for the crash time is
Jul 26, 2022, 9:41:09 PM
Jul 24, 2022, 6:37:01 PM
Jul 24, 2022, 5:25:50 PM
3 crashes for this specific user.
[This should correlate with the message time]

I can't reproduce on my end so i can't send the verbose level logs.
---- 
Will check with the back end developers for relevant sids.
To send more details.

**Comment by berkus** [comment]
Hi, yeah, the local crash time does not help in any way for figuring out what happened on the client device.

If you have set up Firebase Crashlytics for your app it makes sense to fetch the crash report from there. The demo app has [an example on how to configure](https://github.com/twilio/twilio-conversations-demo-android-kotlin#optionally-setup-firebase-crashlytics) that.

**Comment by berkus** [comment]
This is too old, closing.
